steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/docker-gke-project-sainadha/gcp-devops-repo/gcp-devops-app:$BUILD_ID
      - .

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/docker-gke-project-sainadha/gcp-devops-repo/gcp-devops-app:$BUILD_ID

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/gcp-devops-app
      - app=us-central1-docker.pkg.dev/docker-gke-project-sainadha/gcp-devops-repo/gcp-devops-app:$BUILD_ID
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gcp-devops-cluster'
